# Global experiment configuration

generator.seed=42
generator.streamId=stream_abc123

# Number of pipeline iterations per experiment (for performance averaging)
pipeline.iterations=10

# Array sizes per frame
generator.audioLen=10
generator.pixelsLen=10
generator.metadataLen=10

# Experiment parameters
experiment.formats=JSON,BSON
experiment.chunkSizes=100,200,500,1000,2000,3000
experiment.framesPerChunk=100,200,500,1000,2000,3000
