# Configurações do Payload Generator
generator.seed=42
generator.streamId=stream_abc123

# FORMATO DE SERIALIZAÇÃO: JSON ou BSON
# JSON = Formato texto (padrão)
# BSON = Formato binário (para comparação de performance) 
serialization.format= JSON

# Número de iterações para a pipeline (para calcular média de performance)
pipeline.iterations=5

# OPÇÃO 1: 1.000 DADOS (Ex: 10 chunks x 100 frames) - DESCOMENTAR PARA USAR
#generator.nameFile=experiment_payload_1
#generator.numChunks=10
#generator.framesPerChunk=100

# OPÇÃO 2: 10.000 DADOS (100 chunks x 100 frames)
#generator.nameFile=experiment_payload_2
#generator.numChunks=100
#generator.framesPerChunk=100

# OPÇÃO 3: 100.000 DADOS (1.000 chunks x 100 frames)
#generator.nameFile=experiment_payload_3
#generator.numChunks=1000
#generator.framesPerChunk=100

# OPÇÃO 4: 400.000 DADOS (4.000 chunks x 100 frames)
generator.nameFile=experiment_payload_4
generator.numChunks=4000
generator.framesPerChunk=100


# OPÇÃO TESTE PESADO: Menos dados, mas cada dado é gigante (1.000 itens por frame)
#generator.nameFile=payload_heavy.json
#generator.numChunks=10
#generator.framesPerChunk=10
#generator.audioLen=1000
#generator.pixelsLen=1000
#generator.metadataLen=500


generator.audioLen=10
generator.pixelsLen=10
generator.metadataLen=10
