# Configurações do Payload Generator
generator.seed=42
generator.streamId=stream_abc123

# OPÇÃO 1: 100 DADOS (Ex: 10 chunks x 10 frames)
#generator.nameFile=payload_100.json
#generator.numChunks=10
#generator.framesPerChunk=10

# OPÇÃO 2: 1.000 DADOS (Ex: 10 chunks x 100 frames) - DESCOMENTAR PARA USAR
#generator.nameFile=payload_1000.json
#generator.numChunks=10
#generator.framesPerChunk=100

# OPÇÃO 3: 10.000 DADOS (100 chunks x 100 frames)
# generator.nameFile=payload_10k.json
# generator.numChunks=100
# generator.framesPerChunk=100

# OPÇÃO 4: 100.000 DADOS (1.000 chunks x 100 frames)
#generator.nameFile=payload_100k.json
#generator.numChunks=1000
#generator.framesPerChunk=100

# OPÇÃO 5: 1.000.000 DADOS (10.000 chunks x 100 frames) - CUIDADO: PODE DAR OutOfMemory
generator.nameFile=payload_1M.json
generator.numChunks=10000
generator.framesPerChunk=100

# OPÇÃO TESTE PESADO: Menos dados, mas cada dado é gigante (1.000 itens por frame)
# generator.nameFile=payload_heavy.json
# generator.numChunks=10
# generator.framesPerChunk=10
# generator.audioLen=1000
# generator.pixelsLen=1000
# generator.metadataLen=500


generator.audioLen=10
generator.pixelsLen=15
generator.metadataLen=5
